apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      nodePort: 30012
  selector:
    io.kompose.service: postgres
  type: NodePort
