apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  ports:
    - name: "5050"
      port: 5050
      targetPort: 80
      nodePort: 30016
  selector:
    io.kompose.service: pgadmin
  type: NodePort
