apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
    - name: "3050"
      port: 3050
      targetPort: 3000
      nodePort: 30010
  selector:
    io.kompose.service: grafana
  type: NodePort
