apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: maildev
  name: maildev
spec:
  ports:
    - name: "1080"
      port: 1080
      targetPort: 1080
      nodePort: 30017
  selector:
    io.kompose.service: maildev
  type: NodePort
