apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: configserver
  name: configserver
spec:
  ports:
    - name: "9296"
      port: 9296
      targetPort: 9296
      nodePort: 30002
  selector:
    io.kompose.service: configserver
  type: NodePort
