apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: authclient
  name: authclient
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    io.kompose.service: authclient
  type: NodePort
