apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: authclient
  name: authclient
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authclient
  template:
    metadata:
      labels:
        io.kompose.service: authclient
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://serviceregistry:8761/eureka
            - name: OAUTH2_ISSUER_URI
              value: http://authserverinmemory:9000
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configserver:9296
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/barbershop
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
          image: amberex/authclient_in_memory
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - localhost:8080/actuator/health
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          name: authclient
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
