apiVersion: v1
kind: Service
metadata:
  name: authclient
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authclient
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: authserverinmemory
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserverinmemory
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: customerorder
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerorder
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: notifications
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: serviceregistry
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceregistry
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: userinterface
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinterface
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: maildev
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
