apiVersion: v1
kind: Service
metadata:
  name: authclient
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authclient
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: authserverinmemory
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserverinmemory
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: customerorder
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerorder
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: notifications
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: serviceregistry
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceregistry
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: userinterface
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinterface
spec:
  replicas: 3
