apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
      nodePort: 30018
  selector:
    io.kompose.service: zipkin
  type: NodePort
