apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: serviceregistry
  name: serviceregistry
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
      nodePort: 30001
  selector:
    io.kompose.service: serviceregistry
  type: NodePort
