apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: serviceregistry
  name: serviceregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: serviceregistry
  template:
    metadata:
      labels:
        io.kompose.service: serviceregistry
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: amberex/service_registry
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8761/actuator/health || exit 1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          name: serviceregistry
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
