apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  template:
    metadata:
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"

            # Server configuration
            # - name: ZOOKEEPER_SERVER_ID
            #   value: "1"
            # - name: ZOOKEEPER_SERVERS
            #   value: "server.1=zookeeper-0.zookeeper-headless.default.svc.cluster.local:2888:3888"

            # Additional configuration
            # - name: ZOOKEEPER_INIT_LIMIT
            #   value: "5"
            # - name: ZOOKEEPER_SYNC_LIMIT
            #   value: "2"

            # Enable admin server
            # - name: KAFKA_OPTS
            #   value: "-Dzookeeper.admin.enableServer=true -Dzookeeper.admin.serverPort=8080"
              
          # resources:
          #   requests:
          #     cpu: 250m
          #     memory: 512Mi
          #   limits:
          #     cpu: 500m
          #     memory: 1Gi
          
          ports:
            - containerPort: 2181
              # name: client
            # - containerPort: 2888
            #   name: follower
            # - containerPort: 3888
            #   name: election

          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - "echo ruok | nc localhost 2181 | grep imok"
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   failureThreshold: 5
          #   timeoutSeconds: 5

          # readinessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - "echo ruok | nc localhost 2181 | grep imok"
          #   initialDelaySeconds: 15
          #   periodSeconds: 15
          #   failureThreshold: 3
          #   timeoutSeconds: 5
            
      restartPolicy: Always
