apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: notificationservice
  name: notificationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notificationservice
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: notificationservice
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://serviceregistry:8761/eureka
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configserver:9296
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/barbershop
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: kafka:9092
          image: amberex/notification_service
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8040/actuator/health || exit 1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          name: notificationservice
          ports:
            - containerPort: 8040
              protocol: TCP
      restartPolicy: Always
