apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: notificationservice
  name: notificationservice
spec:
  ports:
    - name: "8040"
      port: 8040
      targetPort: 8040
      nodePort: 30009
  selector:
    io.kompose.service: notificationservice
  type: NodePort
