apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: notifications
  name: notifications
spec:
  ports:
    - name: "8040"
      port: 8040
      targetPort: 8040
      nodePort: 30009
  selector:
    io.kompose.service: notifications
  type: NodePort
