apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.default.svc.cluster.local:2181"

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"  
            - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: "60000"

          resources:
            requests:
              cpu: "1"
              memory: 4Gi
            limits:
              cpu: "1"
              memory: 4Gi

          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - "kafka-broker-api-versions --bootstrap-server=localhost:9092 || exit 1"
          #   initialDelaySeconds: 180
          #   periodSeconds: 30
          #   failureThreshold: 5

          # readinessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - "kafka-topics --bootstrap-server=localhost:9092 --list || exit 1"
          #   initialDelaySeconds: 120
          #   periodSeconds: 15
          #   failureThreshold: 3
          #   timeoutSeconds: 10
      restartPolicy: Always
