apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: plaintext
  selector:
    io.kompose.service: kafka
    appp: kafka
  type: NodePort
