apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: payments
  name: payments
spec:
  ports:
    - name: "8060"
      port: 8060
      targetPort: 8060
      nodePort: 30008
  selector:
    io.kompose.service: payments
  type: NodePort
