apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: customerorder
  name: customerorder
spec:
  ports:
    - name: "8042"
      port: 8042
      targetPort: 8042
      nodePort: 30007
  selector:
    io.kompose.service: customerorder
  type: NodePort
