apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
      nodePort: 30013
  selector:
    io.kompose.service: mongo
  type: NodePort
