apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:latest
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            failureThreshold: 10
            periodSeconds: 20
            timeoutSeconds: 20
          name: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
