apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: paymentservice
  name: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: paymentservice
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: paymentservice
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://serviceregistry:8761/eureka
            - name: OAUTH2_ISSUER_URI
              value: http://authserverinmemory:9000
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configserver:9296
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/barbershop
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
          image: amberex/paymentservice
          name: paymentservice
          ports:
            - containerPort: 8060
              protocol: TCP
      restartPolicy: Always
