apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: userinterface
  name: userinterface
spec:
  ports:
    - name: "8766"
      port: 8766
      targetPort: 8766
      nodePort: 30006
  selector:
    io.kompose.service: userinterface
  type: NodePort
